/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juice_corner;

/**
 *
 * @author Haniya
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtOrderNumber = new javax.swing.JTextField();
        txtOrder = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        btnDisplay = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DashBoard");
        setResizable(false);

        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Order Number:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(380, 110, 260, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Order:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(480, 160, 90, 29);

        txtOrderNumber.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel3.add(txtOrderNumber);
        txtOrderNumber.setBounds(569, 109, 164, 30);

        txtOrder.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel3.add(txtOrder);
        txtOrder.setBounds(570, 160, 164, 30);

        btnInsert.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juice_corner/insert.png"))); // NOI18N
        btnInsert.setText("Save");
        jPanel3.add(btnInsert);
        btnInsert.setBounds(340, 240, 90, 34);

        btnDisplay.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnDisplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juice_corner/eye.png"))); // NOI18N
        btnDisplay.setText("Display");
        jPanel3.add(btnDisplay);
        btnDisplay.setBounds(440, 240, 100, 34);

        btnDelete.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juice_corner/delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        jPanel3.add(btnDelete);
        btnDelete.setBounds(549, 240, 100, 34);

        btnCancel.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juice_corner/close.png"))); // NOI18N
        btnCancel.setText("Cancel");
        jPanel3.add(btnCancel);
        btnCancel.setBounds(660, 240, 100, 34);

        tblData.setBackground(new java.awt.Color(102, 102, 102));
        tblData.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tblData.setForeground(new java.awt.Color(255, 255, 255));
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Name", "Order"
            }
        ));
        tblData.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tblData);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(330, 290, 452, 130);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juice_corner/Dropshipping-Juice-Shop-Custom-3D-Photo-Wallpaper-Hand-Painted-Blackboard-Fruit-Coffee-Shop-Wall-Cold-Drink.jpg_q50.jpg"))); // NOI18N
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnInsert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txtOrder;
    private javax.swing.JTextField txtOrderNumber;
    // End of variables declaration//GEN-END:variables
}
